/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"

/*
 * DECLARATIONS
 */
extern_c struct VClass_dsource_idx3l Vt_dsource_idx3l;
struct CClass_dsource_idx3l;
extern_c struct VClass_dsource Vt_dsource;
struct CClass_dsource;
extern_c struct VClass_object Vt_object;
struct CClass_object;
struct CClass_dsource_mnist
{
  struct VClass_dsource_mnist *Vtbl;
  int current;
  struct idx *inputs;
  struct idx *labels;
  int width;
  int height;
  flt bias;
  flt coeff;
};
struct CClass_idx3_state;
struct VClass_dsource_mnist
{
  void *Cdoc;
  void (*Cdestroy) (gptr);
  char (*M_dsource) (struct CClass_dsource *);
  int (*M_size) (struct CClass_dsource_mnist *);
    real (*M_seek) (struct CClass_dsource *, int);
  int (*M_tell) (struct CClass_dsource *);
  int (*M_next) (struct CClass_dsource *);
  char (*M_fprop) (struct CClass_dsource_mnist *, struct CClass_idx3_state *,
		   struct idx *);
  char (*M_dsource_mnist) (struct CClass_dsource_mnist *, struct idx *,
			   struct idx *, int, int, flt, flt);
};
extern_c struct VClass_dsource_mnist Vt_dsource_mnist;
struct CClass_idx_state;
struct CClass_gb_state;
struct CClass_idx3_state
{
  struct VClass_idx3_state *Vtbl;
  struct idx *x;
};
struct VClass_idx3_state
{
  void *Cdoc;
  void (*Cdestroy) (gptr);
  char (*M_idx3_state) (struct CClass_idx3_state *, int, int, int,
			struct idx *, struct srg *);
  char (*M_resize) (struct CClass_idx3_state *, int, int, int);
};
extern_c struct VClass_idx3_state Vt_idx3_state;
extern_c struct idx *C_idx_f3fill (struct idx *, flt);
extern_c struct idx *C_idx_f3addc (struct idx *, flt, struct idx *);
extern_c struct idx *C_idx_f3dotc (struct idx *, flt, struct idx *);
extern_c char C_dsource_C_dsource (struct CClass_dsource *);
extern_c int C_size_C_dsource_mnist (struct CClass_dsource_mnist *);
extern_c real C_seek_C_dsource (struct CClass_dsource *, int);
extern_c int C_tell_C_dsource (struct CClass_dsource *);
extern_c int C_next_C_dsource (struct CClass_dsource *);
extern_c char C_fprop_C_dsource_mnist (struct CClass_dsource_mnist *,
				       struct CClass_idx3_state *,
				       struct idx *);
extern_c char C_dsource_mnist_C_dsource_mnist (struct CClass_dsource_mnist *,
					       struct idx *, struct idx *,
					       int, int, flt, flt);

/* ---------------------------------------- */

/*
 * METHOD FUNCTION dsource-mnist (class dsource-mnist)
 */
extern_c char
C_dsource_mnist_C_dsource_mnist (struct CClass_dsource_mnist *L1_this,
				 struct idx *L1_inp, struct idx *L1_lbl,
				 int L1_w, int L1_h, flt L1_b, flt L1_c)
{
  TRACE_PUSH ("C_dsource_mnist_C_dsource_mnist");
  {
    L1_this->bias = L1_b;
    L1_this->coeff = L1_c;
    L1_this->width = L1_w;
    L1_this->height = L1_h;
    L1_this->current = 0;
    L1_this->inputs = L1_inp;
    L1_this->labels = L1_lbl;
    TRACE_POP ("C_dsource_mnist_C_dsource_mnist");
    return 0;
  }
}

/*
 * METHOD FUNCTION size (class dsource-mnist)
 */
extern_c int
C_size_C_dsource_mnist (struct CClass_dsource_mnist *L1_this)
{
  TRACE_PUSH ("C_size_C_dsource_mnist");
  {
    int L_Tmp0;
    L_Tmp0 = (L1_this->inputs)->dim[0];
    TRACE_POP ("C_size_C_dsource_mnist");
    return L_Tmp0;
  }
}

/*
 * METHOD FUNCTION fprop (class dsource-mnist)
 */
extern_c char
C_fprop_C_dsource_mnist (struct CClass_dsource_mnist *L1_this,
			 struct CClass_idx3_state *L1_out, struct idx *L1_lbl)
{
  TRACE_PUSH ("C_fprop_C_dsource_mnist");
  {
    char L_Tmp0;
    Midx_declare0 (L1_1_4_select);
    struct idx *L_Tmp16;
    (L1_1_4_select)->ndim = 0;
    (L1_out)->Vtbl->M_resize (L1_out, 1, L1_this->height, L1_this->width);
    {
      struct idx *L2_2_outx;
      real L2_3_ni;
      real L2_4_nj;
      real L2_5_di;
      real L2_6_dj;
      Midx_declare (L2_7_0_select, 2);
      Midx_declare (L3_8_3_clone, 2);
      struct idx *L_Tmp9;
      Midx_init (L2_7_0_select, 2);
      Midx_init (L3_8_3_clone, 2);
      L2_2_outx = L1_out->x;
      L2_3_ni = (L1_this->inputs)->dim[1];
      L2_4_nj = (L1_this->inputs)->dim[2];
      L2_5_di = (0.5 * (L1_this->height - L2_3_ni));
      L2_6_dj = (0.5 * (L1_this->width - L2_4_nj));
      C_idx_f3fill (L2_2_outx, (L1_this->bias * L1_this->coeff));
      RTERR_GEN ((((int) L1_this->current) < 0), "illegal parameter");
      RTERR_GEN ((((int) L1_this->current) >=
		  (L1_this->inputs)->dim[((int) 0)]),
		 "specified subscript is too large");
      Midx_select (L2_7_0_select, L1_this->inputs, ((int) 0),
		   ((int) L1_this->current), unsigned char);
      {
	Midx_declare (L4_10_2_clone, 2);
	struct idx *L3_11___m;
	struct idx *L_Tmp12;
	Midx_init (L4_10_2_clone, 2);
	{
	  Midx_declare (L4_13_1_select, 2);
	  struct idx *L4_14___m;
	  struct idx *L_Tmp15;
	  Midx_init (L4_13_1_select, 2);
	  RTERR_GEN ((((int) 0) >= (L2_2_outx)->dim[((int) 0)]),
		     "specified subscript is too large");
	  Midx_select (L4_13_1_select, L2_2_outx, ((int) 0), ((int) 0), flt);
	  L_Tmp15 = L4_13_1_select;
	  Midx_clone2 (L4_10_2_clone, L_Tmp15);
	  L4_14___m = L4_10_2_clone;
	  RTERR_GEN ((((int) L2_3_ni) < 1
		      || ((int) L2_5_di) < 0), "illegal 'size' or 'offset'");
	  RTERR_GEN ((((int) L2_5_di) + ((int) L2_3_ni) >
		      (L4_14___m)->dim[((int) 0)]),
		     "specified interval is too large");
	  Midx_narrow (L4_14___m, ((int) 0), ((int) L2_3_ni), ((int) L2_5_di),
		       flt);
	  L_Tmp12 = L4_14___m;
	}
	Midx_clone2 (L3_8_3_clone, L_Tmp12);
	L3_11___m = L3_8_3_clone;
	RTERR_GEN ((((int) L2_4_nj) < 1
		    || ((int) L2_6_dj) < 0), "illegal 'size' or 'offset'");
	RTERR_GEN ((((int) L2_6_dj) + ((int) L2_4_nj) >
		    (L3_11___m)->dim[((int) 1)]),
		   "specified interval is too large");
	Midx_narrow (L3_11___m, ((int) 1), ((int) L2_4_nj), ((int) L2_6_dj),
		     flt);
	L_Tmp9 = L3_11___m;
      }
      check_main_maout (L2_7_0_select, L_Tmp9);
      Midx_m2copy (L2_7_0_select, L_Tmp9, unsigned char, flt);
      C_idx_f3addc (L2_2_outx, L1_this->bias, L2_2_outx);
      C_idx_f3dotc (L2_2_outx, L1_this->coeff, L2_2_outx);
    }
    RTERR_GEN ((((int) L1_this->current) < 0), "illegal parameter");
    RTERR_GEN ((((int) L1_this->current) >=
		(L1_this->labels)->dim[((int) 0)]),
	       "specified subscript is too large");
    Midx_select (L1_1_4_select, L1_this->labels, ((int) 0),
		 ((int) L1_this->current), unsigned char);
    L_Tmp16 = L1_1_4_select;
    *IDX_PTR (L1_lbl, int) = *IDX_PTR (L_Tmp16, unsigned char);
    L_Tmp0 = 0;
    TRACE_POP ("C_fprop_C_dsource_mnist");
    return L_Tmp0;
  }
}

/*
 * CLASS dsource-mnist DESTROY
 */
static void
Cdestroy_C_dsource_mnist (gptr g)
{
  struct VClass_object *super =
    (struct VClass_object *) (char *) (&Vt_dsource_idx3l);
  super->Cdestroy (g);
}

/*
 * CLASS dsource-mnist VTABLE
 */
struct VClass_dsource_mnist Vt_dsource_mnist = {
  (void *) &Vt_dsource_idx3l,
  &Cdestroy_C_dsource_mnist,
  &C_dsource_C_dsource,
  &C_size_C_dsource_mnist,
  &C_seek_C_dsource,
  &C_tell_C_dsource,
  &C_next_C_dsource,
  &C_fprop_C_dsource_mnist,
  &C_dsource_mnist_C_dsource_mnist,
};

/* ---------------------------------------- */

#ifndef NOLISP

/* Declarations */
extern_c dhclassdoc_t Kc_dsource_idx3l_Rb5bf0a60;
extern_c dhclassdoc_t Kc_dsource_mnist_R3f1f33ac;
extern_c dhclassdoc_t Kc_idx3_state_R344e53eb;
extern_c dhdoc_t K_idx_f3fill_R7d02cabd;
extern_c dhdoc_t K_idx_f3addc_R2764f820;
extern_c dhdoc_t K_idx_f3dotc_R2764f820;

/*
 * METHOD STUB dsource-mnist (class dsource-mnist)
 */
DH (X_dsource_mnist_C_dsource_mnist)
{
  dharg ret;
  ret.dh_char =
    C_dsource_mnist_C_dsource_mnist ((struct CClass_dsource_mnist *) a[1].
				     dh_obj_ptr, a[2].dh_idx_ptr,
				     a[3].dh_idx_ptr, a[4].dh_int,
				     a[5].dh_int, a[6].dh_flt, a[7].dh_flt);
  return ret;
}

/*
 * METHOD DHDOC dsource-mnist (class dsource-mnist)
 */
DHDOC (K_dsource_mnist_C_dsource_mnist_Rdce512c5,
       X_dsource_mnist_C_dsource_mnist, "C_dsource_mnist_C_dsource_mnist", 0,
       0) =
{
DH_FUNC (7),
    DH_OBJ (Kc_dsource_mnist_R3f1f33ac),
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_READ),
    DH_UBYTE,
    DH_IDX (DHT_READ, 1),
    DH_SRG (DHT_READ),
    DH_UBYTE,
    DH_INT, DH_INT, DH_FLT, DH_FLT, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB size (class dsource-mnist)
 */
DH (X_size_C_dsource_mnist)
{
  dharg ret;
  ret.dh_int =
    C_size_C_dsource_mnist ((struct CClass_dsource_mnist *) a[1].dh_obj_ptr);
  return ret;
}

/*
 * METHOD DHDOC size (class dsource-mnist)
 */
DHDOC (K_size_C_dsource_mnist_R59e87308, X_size_C_dsource_mnist,
       "C_size_C_dsource_mnist", 0, 0) =
{
DH_FUNC (1),
    DH_OBJ (Kc_dsource_mnist_R3f1f33ac),
    DH_RETURN, DH_INT, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB fprop (class dsource-mnist)
 */
DH (X_fprop_C_dsource_mnist)
{
  dharg ret;
  ret.dh_char =
    C_fprop_C_dsource_mnist ((struct CClass_dsource_mnist *) a[1].dh_obj_ptr,
			     (struct CClass_idx3_state *) a[2].dh_obj_ptr,
			     a[3].dh_idx_ptr);
  return ret;
}

/*
 * METHOD DHDOC fprop (class dsource-mnist)
 */
DHDOC (K_fprop_C_dsource_mnist_R6358ee5c, X_fprop_C_dsource_mnist,
       "C_fprop_C_dsource_mnist", 0, 0) =
{
DH_FUNC (3),
    DH_OBJ (Kc_dsource_mnist_R3f1f33ac),
    DH_OBJ (Kc_idx3_state_R344e53eb),
    DH_IDX (DHT_WRITE, 0),
    DH_SRG (DHT_WRITE),
    DH_INT,
    DH_RETURN,
    DH_BOOL,
    DH_END_FUNC,
    DH_REFER (Kc_idx3_state_R344e53eb),
    DH_REFER (K_idx_f3fill_R7d02cabd),
    DH_REFER (K_idx_f3addc_R2764f820),
    DH_REFER (K_idx_f3dotc_R2764f820), DH_NIL};

/*
 * CLASS dsource-mnist DHCLASSDOC
 */
DHCLASSDOC (Kc_dsource_mnist_R3f1f33ac, &Kc_dsource_idx3l_Rb5bf0a60,
	    dsource_mnist, "dsource-mnist", Vt_dsource_mnist, 3) =
{
DH_CLASS (6, Kc_dsource_mnist_R3f1f33ac),
    DH_NAME ("inputs", dsource_mnist, inputs),
    DH_IDX (DHT_READ, 3),
    DH_SRG (DHT_READ),
    DH_UBYTE,
    DH_NAME ("labels", dsource_mnist, labels),
    DH_IDX (DHT_READ, 1),
    DH_SRG (DHT_READ),
    DH_UBYTE,
    DH_NAME ("width", dsource_mnist, width),
    DH_INT,
    DH_NAME ("height", dsource_mnist, height),
    DH_INT,
    DH_NAME ("bias", dsource_mnist, bias),
    DH_FLT,
    DH_NAME ("coeff", dsource_mnist, coeff),
    DH_FLT,
    DH_END_CLASS,
    DH_METHOD ("dsource_mnist", K_dsource_mnist_C_dsource_mnist_Rdce512c5),
    DH_METHOD ("size", K_size_C_dsource_mnist_R59e87308),
    DH_METHOD ("fprop", K_fprop_C_dsource_mnist_R6358ee5c), DH_NIL};

/*
 * INIT FUNCTION
 */
extern_c void
init_dsource_mnist (void)
{
  dhclass_define ("dsource-mnist", &Kc_dsource_mnist_R3f1f33ac);
  dhmethod_define (&Kc_dsource_mnist_R3f1f33ac, "dsource-mnist",
		   &K_dsource_mnist_C_dsource_mnist_Rdce512c5);
  dhmethod_define (&Kc_dsource_mnist_R3f1f33ac, "size",
		   &K_size_C_dsource_mnist_R59e87308);
  dhmethod_define (&Kc_dsource_mnist_R3f1f33ac, "fprop",
		   &K_fprop_C_dsource_mnist_R6358ee5c);
}

int majver_dsource_mnist = 40;
int minver_dsource_mnist = 10;

#endif
